# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [35]:
import numpy as np
a=np.zeros((2,3))
b=np.empty((2,3))

#empty會建立很接近0的數值, zeros會建立0的數值
#empty必須讓使用者輸入數值，zeros是建立可以使用的0在array



float64
complex128
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [2]:
# 參考解答
a = np.random.rand(2, 3)
dec_1=a%1
a-dec_1



array([[0., 0., 0.],
       [0., 0., 0.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [3]:
m = 20
n = 40

b=a*(n-m)
dec=b%1
(b-dec)+m

array([[26., 23., 31.],
       [36., 38., 24.]])

PT.2
題目:<br>
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']<br>
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']<br>
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]<br>
rank_list = [8,1,5,4,7,6,2,3]<br>
myopia_list = [True,True,False,False,True,True,False,False]<br>
1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]<br>
2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重




In [31]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]
dt=np.dtype({'names':('name', 'sex', 'weight', 'rank', 'myopia'),'formats':('U10','U6',np.float_,np.int_,np.bool_)})
a=np.zeros(8,dtype=dt)
a['name']=name_list
a['sex']=sex_list
a['weight']=weight_list
a['rank']=rank_list
a['myopia']=myopia_list


a

array([('小明', 'boy', 67.5, 8,  True), ('小華', 'boy', 75.3, 1,  True),
       ('小菁', 'girl', 50.1, 5, False), ('小美', 'girl', 45.5, 4, False),
       ('小張', 'boy', 80.8, 7,  True), ('John', 'boy', 90.4, 6,  True),
       ('Mark', 'boy', 78.4, 2, False), ('Tom', 'boy', 70.7, 3, False)],
      dtype=[('name', '<U10'), ('sex', '<U6'), ('weight', '<f8'), ('rank', '<i8'), ('myopia', '?')])

In [46]:

np.average(a['weight'])

array([0, 1, 4, 5, 6, 7])

In [47]:
boy_index = np.where(a['sex']=='boy')[0]
np.mean(a['weight'][boy_index])

77.18333333333332

In [48]:
girl_index=np.where(a['sex']=='girl')[0]
np.mean(a['weight'][girl_index])

47.8